=== MahmoudAlshahaly/xml/1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT family (grandfather)>
<!ELEMENT grandfather (#PCDATA|father|uncle|aunt)*>
<!ELEMENT father (#PCDATA|mother|doughter|son)*>
<!ELEMENT mother (#PCDATA)>
<!ELEMENT doughter (#PCDATA)>
<!ELEMENT son (#PCDATA)>
<!ELEMENT uncle (#PCDATA)>
<!ELEMENT aunt (#PCDATA)>

<!ATTLIST father jop (engineer|acountant|doctor) "engineer">
<!ATTLIST doughter jop (engineer|acountant|doctor) "engineer">

<!ATTLIST son age CDATA #REQUIRED>
<!ATTLIST doughter age CDATA #REQUIRED>

<!ATTLIST son sport (football|tennis) "football">
<!ATTLIST aunt sons CDATA "2">

=== MahmoudAlshahaly/xml/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE family SYSTEM "D:\XML\DAY1\1.dtd">
<family>
	<grandfather>ahmed
        <father jop="engineer">ayman
		    <mother>aya</mother>
			<doughter age="22" jop="engineer">nora</doughter>
			<son age="20" sport="football">yasser</son>
		</father>
		<uncle>khalid</uncle>
		<uncle>eslam</uncle>
		<aunt sons="2">sara</aunt>
	</grandfather>
</family>
